# PreToolUse hook (Edit|Write): frontend/wailsjs is generated by `wails build` —
# a hand-edit is always a mistake (root CLAUDE.md "Enforcement"). Exit 2 blocks it.
$raw = [Console]::In.ReadToEnd()
$path = $null
try { $path = ($raw | ConvertFrom-Json).tool_input.file_path } catch {}
if (-not $path) {
    # Unparseable input: fail toward blocking if the payload names the generated dir.
    if ($raw -match 'frontend[\\/]+wailsjs[\\/]') { $path = $raw } else { exit 0 }
}
if (($path -replace '\\', '/') -match '(^|/)frontend/wailsjs/') {
    [Console]::Error.WriteLine("frontend/wailsjs is generated - never hand-edit. Change the bound Go code and run 'wails build' to regenerate the bindings.")
    exit 2
}
exit 0
