// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {stats} from '../models';
import {http} from '../models';
import {app} from '../models';
import {analytics} from '../models';
import {geo} from '../models';
import {config} from '../models';
import {logging} from '../models';

export function AgentBandwidthHistory(arg1:string,arg2:number,arg3:number):Promise<stats.HistoryResult>;

export function AvatarHandler():Promise<http.Handler>;

export function BandwidthHistory(arg1:number,arg2:number):Promise<stats.HistoryResult>;

export function BrowseMMDB(arg1:string):Promise<string>;

export function ChooseAndInspectSetupFile():Promise<app.SetupFileInfo>;

export function CreatorAvatar():Promise<string>;

export function CreatorInfo():Promise<Record<string, string>>;

export function ExportDiagnostics():Promise<string>;

export function ExportSetup(arg1:string):Promise<string>;

export function FirewallRepair():Promise<void>;

export function FirewallStatus():Promise<boolean>;

export function GeoSnapshot(arg1:number):Promise<Array<analytics.CountryAgg>>;

export function GeoStatus():Promise<geo.Status>;

export function GetConfig():Promise<config.Config>;

export function HandleDeepLink(arg1:string):Promise<void>;

export function ImportSetup(arg1:string,arg2:string):Promise<void>;

export function InstallService():Promise<void>;

export function LogsSince(arg1:number):Promise<Array<logging.Entry>>;

export function MeasureLatency():Promise<app.LatencyResult>;

export function OnSecondInstance(arg1:string):Promise<void>;

export function OpenConfigDir():Promise<void>;

export function OpenCreatorURL():Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function PairingCode():Promise<string>;

export function PeakMatrix(arg1:number):Promise<analytics.PeakMatrix>;

export function PeerStats():Promise<Array<stats.PeerStat>>;

export function PlayerDetail(arg1:string):Promise<analytics.PlayerDetail>;

export function PlayerHistory(arg1:string,arg2:number):Promise<Array<analytics.TrafficPoint>>;

export function PlayerLatency(arg1:string,arg2:number):Promise<Array<analytics.LatencyPoint>>;

export function Players(arg1:analytics.PlayersQuery):Promise<analytics.PlayersPage>;

export function RegenerateToken():Promise<void>;

export function RestartEngine():Promise<void>;

export function SaveSettings(arg1:config.Config):Promise<void>;

export function SaveTunnels(arg1:Array<config.Tunnel>):Promise<void>;

export function ServiceStatus():Promise<string>;

export function SessionTimeline(arg1:number):Promise<analytics.SessionTimeline>;

export function Sessions(arg1:analytics.SessionsQuery):Promise<analytics.SessionsPage>;

export function SetTheme(arg1:string):Promise<void>;

export function SetupAgent(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SetupGateway(arg1:string):Promise<void>;

export function Status():Promise<app.UIStatus>;

export function Summary(arg1:number):Promise<analytics.Summary>;

export function TakePendingDeepLink():Promise<string>;

export function TestReachability(arg1:string):Promise<string>;

export function TunnelUptime(arg1:number):Promise<analytics.UptimeReport>;

export function UninstallService():Promise<void>;

export function Version():Promise<string>;
