// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AgentBandwidthHistory(arg1, arg2, arg3) {
  return window['go']['app']['App']['AgentBandwidthHistory'](arg1, arg2, arg3);
}

export function AvatarHandler() {
  return window['go']['app']['App']['AvatarHandler']();
}

export function BandwidthHistory(arg1, arg2) {
  return window['go']['app']['App']['BandwidthHistory'](arg1, arg2);
}

export function BrowseMMDB(arg1) {
  return window['go']['app']['App']['BrowseMMDB'](arg1);
}

export function ChooseAndInspectSetupFile() {
  return window['go']['app']['App']['ChooseAndInspectSetupFile']();
}

export function CreatorAvatar() {
  return window['go']['app']['App']['CreatorAvatar']();
}

export function CreatorInfo() {
  return window['go']['app']['App']['CreatorInfo']();
}

export function ExportDiagnostics() {
  return window['go']['app']['App']['ExportDiagnostics']();
}

export function ExportSetup(arg1) {
  return window['go']['app']['App']['ExportSetup'](arg1);
}

export function FirewallRepair() {
  return window['go']['app']['App']['FirewallRepair']();
}

export function FirewallStatus() {
  return window['go']['app']['App']['FirewallStatus']();
}

export function GatewayEvents(arg1) {
  return window['go']['app']['App']['GatewayEvents'](arg1);
}

export function GeoSnapshot(arg1) {
  return window['go']['app']['App']['GeoSnapshot'](arg1);
}

export function GeoStatus() {
  return window['go']['app']['App']['GeoStatus']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function HandleDeepLink(arg1) {
  return window['go']['app']['App']['HandleDeepLink'](arg1);
}

export function ImportSetup(arg1, arg2) {
  return window['go']['app']['App']['ImportSetup'](arg1, arg2);
}

export function InstallService() {
  return window['go']['app']['App']['InstallService']();
}

export function IssuePairingCode(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['IssuePairingCode'](arg1, arg2, arg3, arg4);
}

export function ListAgents() {
  return window['go']['app']['App']['ListAgents']();
}

export function LogsSince(arg1) {
  return window['go']['app']['App']['LogsSince'](arg1);
}

export function MeasureLatency() {
  return window['go']['app']['App']['MeasureLatency']();
}

export function OnSecondInstance(arg1) {
  return window['go']['app']['App']['OnSecondInstance'](arg1);
}

export function OpenConfigDir() {
  return window['go']['app']['App']['OpenConfigDir']();
}

export function OpenCreatorURL() {
  return window['go']['app']['App']['OpenCreatorURL']();
}

export function OpenExternal(arg1) {
  return window['go']['app']['App']['OpenExternal'](arg1);
}

export function PairingCode() {
  return window['go']['app']['App']['PairingCode']();
}

export function PeakMatrix(arg1) {
  return window['go']['app']['App']['PeakMatrix'](arg1);
}

export function PeerStats() {
  return window['go']['app']['App']['PeerStats']();
}

export function PlayerDetail(arg1) {
  return window['go']['app']['App']['PlayerDetail'](arg1);
}

export function PlayerHistory(arg1, arg2) {
  return window['go']['app']['App']['PlayerHistory'](arg1, arg2);
}

export function PlayerLatency(arg1, arg2) {
  return window['go']['app']['App']['PlayerLatency'](arg1, arg2);
}

export function Players(arg1) {
  return window['go']['app']['App']['Players'](arg1);
}

export function RegenerateToken() {
  return window['go']['app']['App']['RegenerateToken']();
}

export function RenameAgent(arg1, arg2) {
  return window['go']['app']['App']['RenameAgent'](arg1, arg2);
}

export function RestartEngine() {
  return window['go']['app']['App']['RestartEngine']();
}

export function RevokeAgent(arg1) {
  return window['go']['app']['App']['RevokeAgent'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SaveTunnels(arg1) {
  return window['go']['app']['App']['SaveTunnels'](arg1);
}

export function ServiceStatus() {
  return window['go']['app']['App']['ServiceStatus']();
}

export function SessionTimeline(arg1) {
  return window['go']['app']['App']['SessionTimeline'](arg1);
}

export function Sessions(arg1) {
  return window['go']['app']['App']['Sessions'](arg1);
}

export function SetAgentScope(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetAgentScope'](arg1, arg2, arg3);
}

export function SetTheme(arg1) {
  return window['go']['app']['App']['SetTheme'](arg1);
}

export function SetupAgent(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetupAgent'](arg1, arg2, arg3);
}

export function SetupGateway(arg1) {
  return window['go']['app']['App']['SetupGateway'](arg1);
}

export function Status() {
  return window['go']['app']['App']['Status']();
}

export function Summary(arg1) {
  return window['go']['app']['App']['Summary'](arg1);
}

export function TakePendingDeepLink() {
  return window['go']['app']['App']['TakePendingDeepLink']();
}

export function TestReachability(arg1) {
  return window['go']['app']['App']['TestReachability'](arg1);
}

export function TunnelUptime(arg1) {
  return window['go']['app']['App']['TunnelUptime'](arg1);
}

export function UninstallService() {
  return window['go']['app']['App']['UninstallService']();
}

export function Version() {
  return window['go']['app']['App']['Version']();
}
