// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {stats} from '../models';
import {app} from '../models';
import {config} from '../models';
import {logging} from '../models';

export function BandwidthHistory(arg1:number,arg2:number):Promise<stats.HistoryResult>;

export function ChooseAndInspectSetupFile():Promise<app.SetupFileInfo>;

export function ExportDiagnostics():Promise<string>;

export function ExportSetup(arg1:string):Promise<string>;

export function FirewallRepair():Promise<void>;

export function FirewallStatus():Promise<boolean>;

export function GetConfig():Promise<config.Config>;

export function ImportSetup(arg1:string,arg2:string):Promise<void>;

export function InstallService():Promise<void>;

export function LogsSince(arg1:number):Promise<Array<logging.Entry>>;

export function OpenConfigDir():Promise<void>;

export function PairingCode():Promise<string>;

export function PeerStats():Promise<Array<stats.PeerStat>>;

export function RegenerateToken():Promise<void>;

export function RestartEngine():Promise<void>;

export function SaveSettings(arg1:config.Config):Promise<void>;

export function SaveTunnels(arg1:Array<config.Tunnel>):Promise<void>;

export function ServiceStatus():Promise<string>;

export function SetTheme(arg1:string):Promise<void>;

export function SetupAgent(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SetupGateway(arg1:string):Promise<void>;

export function Status():Promise<app.UIStatus>;

export function TestReachability(arg1:string):Promise<string>;

export function UninstallService():Promise<void>;

export function Version():Promise<string>;
